// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL02leIYL1Ky4eplXu7fDm8XWk2dIl2c8',
    appId: '1:136134771629:web:44cad207d228dace9ad724',
    messagingSenderId: '136134771629',
    projectId: 'chatapptutorial-bf32a',
    authDomain: 'chatapptutorial-bf32a.firebaseapp.com',
    storageBucket: 'chatapptutorial-bf32a.appspot.com',
    measurementId: 'G-LYN0JCVM6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLn45u7878FSPv3fLPvpzxiOeTuBtT730',
    appId: '1:136134771629:android:e519279a24be66219ad724',
    messagingSenderId: '136134771629',
    projectId: 'chatapptutorial-bf32a',
    storageBucket: 'chatapptutorial-bf32a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy6C2CpYxOke64mgY1r6YuCx5gHNJnDHw',
    appId: '1:136134771629:ios:8d93cb4ae80f2c399ad724',
    messagingSenderId: '136134771629',
    projectId: 'chatapptutorial-bf32a',
    storageBucket: 'chatapptutorial-bf32a.appspot.com',
    iosBundleId: 'com.example.flutter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy6C2CpYxOke64mgY1r6YuCx5gHNJnDHw',
    appId: '1:136134771629:ios:8d93cb4ae80f2c399ad724',
    messagingSenderId: '136134771629',
    projectId: 'chatapptutorial-bf32a',
    storageBucket: 'chatapptutorial-bf32a.appspot.com',
    iosBundleId: 'com.example.flutter1',
  );
}
